### ISSUE TITLE
gold metrics off

### ISSUE THREAD

**Issue by 84adam** [BuyBitcoinWorldwide/Bitbo#2]
As per https://www.gold.org/goldhub/data/how-much-gold there are likely significantly more metric tons of gold as of January, 2022: 205,238 vs. 197,576 (a difference of around 3.88%).

Gold's market cap is higher as a result, at current price of $1837.56/ozt:

`205238 tonnes * 32150.75 ozt/tonne * 1837.56 ozt = 12,125,241,880,707` (12.125 Trillion, 3.99% higher than quoted market cap)

And therefore, the 'Bitcoin vs. Gold Market Cap' figure should be around 2.66% (as opposed to 2.77%).

Other sources may quote different values for the total above ground stocks of gold, but I believe that of `gold.org` to be most likely correct.

**Comment by JTuwiner** [comment]
Thanks for the suggestion! This makes sense, I forward this to the dev team to get this updated

**Comment by JTuwiner** [comment]
<img width="297" alt="Screen Shot 2023-01-05 at 11 45 24 AM" src="https://user-images.githubusercontent.com/2924924/210834469-9181ea29-92d1-4382-9856-6f50ee842213.png">

This has been updated now. How does it look?

Thank you so much for the suggestion. If you have any other ideas or feature requests for the site, please let us know!

**Comment by 84adam** [comment]
Looks great! :)

**Comment by JTuwiner** [comment]
@84adam we're moving to https://github.com/BitboBTC/Feedback in case you have any future suggestions or feedback. Thanks!
